name: Python application Test

on: 
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: install dependencies
      run: |
        pip install pytest

    - name: execute the test script
      run: |
        python -m unittest test_greeter.py

        

        
